CREATE TABLE USERS (
                       USERNAME VARCHAR(128) PRIMARY KEY,
                       PASSWORD VARCHAR(128) NOT NULL,
                       ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
                             USERNAME VARCHAR(128) NOT NULL,
                             AUTHORITY VARCHAR(128) NOT NULL,
                             CONSTRAINT PK_AUTHORITIES PRIMARY KEY (USERNAME, AUTHORITY),
                             CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);

CREATE UNIQUE INDEX IDX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY);